name: on-pr

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
    paths:
      - '.github/workflows/on-pr.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'tests/**'
      - 'functions/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:

  setup:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/setup.yaml@v2.12.2

  validate:
    needs: setup
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.12.2
    with:
      examples: |
        [
          { "example": "examples/autoeksclusters/minimal.yaml" },
          { "example": "examples/autoeksclusters/standard.yaml" },
          { "example": "examples/autoeksclusters/with-network.yaml" },
          { "example": "examples/autoeksclusters/import.yaml" },
          { "example": "examples/autoeksclusters/test/example.yaml", "observed_resources": "examples/autoeksclusters/test/mocks/observed-resources/steps/1" },
          { "example": "examples/autoeksclusters/test/example.yaml", "observed_resources": "examples/autoeksclusters/test/mocks/observed-resources/steps/2" },
          { "example": "examples/autoeksclusters/test/example.yaml", "observed_resources": "examples/autoeksclusters/test/mocks/observed-resources/steps/3" },
          { "example": "examples/autoeksclusters/with-network/test/example.yaml", "observed_resources": "examples/autoeksclusters/with-network/test/mocks/observed-resources/steps/1" }
        ]
      api_path: apis/autoeksclusters
      error_on_missing_schemas: true

  test:
    needs: setup
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.12.2

  e2e:
    needs: setup
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.12.2
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2
      timeout-minutes: 45
      cleanup-timeout-minutes: 60
      debug-resource-types: |
        [
          "network.aws.hops.ops.com.ai"
        ]

  publish:
    needs: 
      - validate
      - test
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v2.12.2
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
